name: Jim
channels:
  - defaults
dependencies:
  - astropy
  - brotli-python
  - contourpy
  - cryptography
  - debugpy
  - executing
  - glib
  - hdf5
  - ipykernel
  - ipython
  - json5
  - jupyter==1.0.0
  - jupyterlab==3.6.3
  - matplotlib
  - mkl
  - mysql
  - notebook==6.5.4
  - numba
  - numpy
  - pandas
  - pillow
  - pip
  - psutil
  - pyqt
  - python==3.11.5
  - scipy
  - seaborn
  - setuptools
  - y-py
  - yaml
  - pip:
    - astroquery
    - autograd
    - build
    - celerite2==0.2.1
    - corner
    - cython
    - h5py
    - html5lib
    - installer
    - keras==2.14.0
    - lightkurve==2.4.2
    - markdown
    - pluggy
    - powerlaw
    - pyastronomy
    - pytest
    - quantities
    - scikit-learn==1.3.2
    - tensorflow==2.14.0
    - tensorflow-estimator==2.14.0
    - tensorflow-io-gcs-filesystem==0.34.0
    - tqdm==4.66.1
    - uncertainties
